export const CATALOG_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 12,
  KEYWORD_SEARCH_DEBOUNCE_MS: 300,
  AI_SEARCH_DEBOUNCE_MS: 450,
  MIN_AI_SEARCH_QUERY_LENGTH: 2,
  DEFAULT_AI_SIMILARITY_THRESHOLD: 0.75,
  DEFAULT_AI_SEARCH_LIMIT: 50,
  CATEGORY_CACHE_REVALIDATE_SECONDS: 60,
} as const;
